


server: 
  port: 8082
  
spring: 
  ## ==============================================================================
  ## DB(PostgreSQL) Connection For R2DBC:[skt_station_db]
  ## ==============================================================================
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=rabbitmq
    username: postgres
    password: postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 3
      max-size: 5

  cloud: 
    ## ==============================================================================
    ## Message Broker(rabbitMQ) Connection to rabbitMQ & exchange, queue naming
    ##                          * adjust "...spring.rabbitmq.host" & 
    ##                            "...spring.rabbitmq.port" &
    ##                            "...spring.rabbitmq.username" & 
    ##                            "...spring.rabbitmq.password" & 
    ##                            for expected rabbitMQ server which want to connect
    ##                          * adjust "...bindings.<channel-name>"
    ##                            <channel-name> for expected channel-name which want to create
    ##                          * adjust "...bindings.<channel-name>.<destination>"
    ##                            <destination> for expected queue name which want to create   
    ## ==============================================================================
    ## `spring.cloud.function.definition: <bean-name>`  |-> 對應 class 方法的 bean 名稱、多筆以分號分隔
    function:
      definition: acceptSignal
    stream:
      binders:
        default-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
      bindings:
        acceptSignal-out-0:
          binder: default-rabbit
          destination: signal-accepted
        acceptSignal-in-0: 
          binder: default-rabbit
          destination: signal-accepted
          group: signal-accepted
          consumer:
            batch-mode: true
      rabbit:
        bindings:
          acceptSignal-in-0:
            consumer:
              enable-batching: true
              batch-size: 5
              receive-timeout: 200
              max-attempts: 3
              acknowledge-mode: MANUAL

          